### PR TITLE
Prevent event propagation on close

### PR DESCRIPTION
**Pull request by knicklabs**
Handy script, thanks a lot for making this. I put this in use on a site today, but had one issue. When the close method was triggered by clicking on the close selector, the click event on the close selector was propagated, resulting in the page scrolling to the top.

I modified the script to pass the click event to the close method so that the event propagation could be stopped. I did not minify the modified script as I was unsure what you were using for minification. If you accept this patch, the script will need to be minified.

### CODE REVIEW

**Comment by crcastle** [comment]
FWIW, I can confirm both that I had the same issue and this pull request fixes it.

EDIT: While this fixes the even propagation problem it seems to create or bring to the surface another bug.  Other elements with click events are no longer working.  Gotta close up for the day, but I'll try to put together a fix soon.

**Comment by knicklabs** [comment]
I checked this out and confirmed that the 'fix' prevents event propagation on other anchor elements. This was indeed a side effect of the code I injected. Thanks for spotting that.

**Comment by tristanoneil** [comment]
Thanks guys. I think we'll pull this one in soon. /cc @seanbehan

**Comment by seanbehan** [comment]
Thanks! I think I'm going to prevent event propagation for close on bind.

``` javascript
/// something like... 
$(settings['open'], this).parent().find(settings['close']).bind('click', function(event){
   event.preventDefault();
   methods.close();
});
```

**Pull request closed without merging**
